$(document).ready(()=>{
  entrypoint();
});

const entrypoint = ()=>{
  $('#6,#7,#8,#9').hide();
  $('#1').on('click',()=>{
    $('#answer').text(data[0].a);
  });
  $('#2').on('click',()=>{
    $('#answer').text(data[1].a);
  });
  $('#3').on('click',()=>{
    $('#answer').text(data[2].a);
  });
  $('#4').on('click',()=>{
    $('#answer').text(data[3].a);
  });
  $('#5').on('click',()=>{
    $('#5').hide();
    $('#6,#7,#8,#9').show();
  });
  $('#6').on('click',()=>{
    $('#answer').text(data[4].a);
  });
  $('#7').on('click',()=>{
    $('#answer').text(data[5].a);
  });
  $('#8').on('click',()=>{
    $('#answer').text(data[6].a);
  });
  $('#9').on('click',()=>{
    $('#6,#7,#8,#9').hide();
    $('#5').show();
    $('#answer').text('');
  });
}
